package "xmonad"
package "xmonad-contrib"
package "xorg-utils"
package "xorg-server-common"
package "scrot"
package "conky"
package "xcompmgr"
package "keychain"
package "hsetroot"
package "disper"
package "xdotool"
package "xdg-utils"
package "transset-df"
package "keepass"
package "gnome-session"
package "gnome-keyring"
package "gnome-settings-daemon"
package "gnome-screensaver"
package "gnome-control-center"
package "gnome-bluetooth"

link "/usr/share/xsessions/custom.desktop" do
  to "#{ENV['PWD']}/../custom-xsession.desktop"
end
